version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=seu_password_admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
